first_name = input("Enter your first name: ").strip().title()
surname = input("Enter your surname:").strip().title()
email = input("Enter your Email:").strip()
phone_number = input("Enter your phone number:").strip()
job_duty = input("Enter your job duty/role:").strip()
company = input("Enter your company/department:").strip()
location = input("Ënter your location/city:").strip()
employee_id = input("Ënter your employee ID:").strip()


# Print a clean, formatted summary
print("\n" + "="*30)
print("       USER PROFILE       ")
print("="*30)
print(f"Full Name:  {first_name} {surname}")
print(f"Employee ID : {employee_id}")
print(f"Phone     :{phone_number}")
print(f"Email     :{email}")
print(f"job Duty   :{job_duty}")
print(f"company    :{company}")
print(f"Location   :{location}")  
print("="*30)
print(f"Thank you for your infomation,{first_name}")
print("Profile created successfully.")